In [83]:
import numpy as np
import scipy.linalg as sl
import time
from scipy.io import loadmat

## Q2 a)
---

In [72]:
def IRLS_M(Y, q, gamma):
    n,p = Y.shape
    epsilon = 1; # regularizing sequence
    
    tol = 10**(-6)  # difference between iterates at termination
    err = 10**6 
    
    X = np.array(Y) # make a copy so operations do not mutate the original
    X[np.isnan(X)] = 0 # Fill in missing entries with zeros
    matrices = []
    for i in range(p):
        s = np.zeros(n)
        for j in range(n):
            if X[j, i] == 0: s[j] = 1
        matrix = np.diag(s)
        matrices.append(matrix)
        
    U,s,VT = np.linalg.svd(X, full_matrices=True)
    epsilon_new = min(epsilon, gamma * s[q]) 
    for i in range(q, n):
        s[i] = max(epsilon_new, s[i]);
    W = U @ np.diag(s**(-1)) @ U.T
    
    k = 0
    while err > tol:
        Xnew = np.zeros((n,0))
        for i in range(p):
            A = matrices[i]
            Xnew = np.column_stack((Xnew, X[:,i] - A @ np.linalg.pinv(A.T @ W @ A) @ A.T @ W @ X[:,i]))
        
        U,s,VT = np.linalg.svd(Xnew, full_matrices=True)
        epsilon_new = min(epsilon, gamma * s[q]) 
        for i in range(q, n):
            s[i] = max(epsilon_new, s[i]);
        # TODO: update W
        # W = 
        
        err = np.linalg.norm(X - Xnew,'fro')
        epsilon = epsilon_new
        X = Xnew
        k = k + 1
    return (X, k)

In [37]:
Xtrue = loadmat("incomplete.mat")["Xtrue"]
Y1 = loadmat("incomplete.mat")["Y1"]
Y2 = loadmat("incomplete.mat")["Y2"]
Y3 = loadmat("incomplete.mat")["Y3"]

In [38]:
print(Xtrue.astype(int))

[[30 12 24  8 12 14 12 12 22 24 14 10 14 24 20 12]
 [30 21 15 11 21 26 12 21 10 15 17 16  8 15 23 12]
 [15  9  9  5  9 11  6  9  7  9  8  7  5  9 11  6]
 [35 16 26 10 16 19 14 16 23 26 17 13 15 26 24 14]
 [15  9  9  5  9 11  6  9  7  9  8  7  5  9 11  6]
 [25 11 19  7 11 13 10 11 17 19 12  9 11 19 17 10]
 [45 24 30 14 24 29 18 24 25 30 23 19 17 30 32 18]
 [30 15 21  9 15 18 12 15 18 21 15 12 12 21 21 12]
 [25 11 19  7 11 13 10 11 17 19 12  9 11 19 17 10]
 [20 13 11  7 13 16  8 13  8 11 11 10  6 11 15  8]
 [45 24 30 14 24 29 18 24 25 30 23 19 17 30 32 18]
 [30 15 21  9 15 18 12 15 18 21 15 12 12 21 21 12]
 [25 17 13  9 17 21 10 17  9 13 14 13  7 13 19 10]
 [40 20 28 12 20 24 16 20 24 28 20 16 16 28 28 16]
 [30 18 18 10 18 22 12 18 14 18 16 14 10 18 22 12]
 [25 11 19  7 11 13 10 11 17 19 12  9 11 19 17 10]]


## Q2 b)
---

In [39]:
X1, k = IRLS_M(Y1, 3, 1)
print('X1')
print(X1.astype(int))
print('Error:', np.linalg.norm((Xtrue - X1), 'fro'))
#print((Xtrue - X1).astype(int))

X1
[[29 11 24  8 12 14 11 13 22 23 13 10 14 24 19 11]
 [29 21 15 10 19 23 11 13 11 15 17 14  8 15 23 11]
 [14  8  9  4  9 10  5  7  7  9  8  6  5  8 10  6]
 [34 16 25 10 16 19 13 16 23 25 17 13 14 26 24 13]
 [14  9  9  4  8 10  5  6  7  9  8  6  5  9 11  5]
 [24 11 19  7 10 13 10 11 16 19 11  9 11 19 16  9]
 [45 23 29 13 23 28 18 21 25 29 22 19 17 30 32 17]
 [29 14 21  9 15 18 11 15 18 20 15 11 12 21 20 12]
 [24 11 18  7 10 13 10 11 17 19 11  9 10 19 16  9]
 [19 13 10  7 12 16  7  9  8 11 11  9  5 10 15  8]
 [45 24 30 14 24 29 18 21 25 29 23 18 16 29 32 18]
 [29 15 20  9 14 18 12 15 18 21 15 12 12 21 21 12]
 [25 16 13  8 17 19 10 11  9 13 14 13  7 13 19 10]
 [38 20 26 12 19 23 16 18 23 26 19 15 16 26 28 16]
 [29 17 18 10 17 22 12 14 14 17 16 13 10 17 21 11]
 [25 11 19  7 11 13  9 11 16 18 11  9 11 18 17  9]]
Error: 12.6938091154


In [40]:
X2, k = IRLS_M(Y2, 3, 1)
print('X2')
print(X2.astype(int))
print('Error:', np.linalg.norm((Xtrue - X2), 'fro'))
#print((Xtrue - X2).astype(int))

X2
[[30 12 24  8 12 14 12 12 22 23 13 10 14 24 20 11]
 [30 21 15 11 21 25 12 21 10 15 17 15  8 15 23 11]
 [14  9  8  4  9 10  5  8  7  9  8  7  5  8 11  6]
 [35 16 25 10 16 19 13 16 23 25 17 13 15 26 24 13]
 [14  9  9  5  8 10  5  8  7  9  8  6  5  9 11  5]
 [24 11 19  7 10 13 10 11 17 19 12  9 11 19 17  9]
 [45 24 30 13 23 29 18 23 25 30 22 19 17 30 32 17]
 [29 14 21  8 15 18 12 15 18 21 15 12 12 21 21 12]
 [25 11 18  7 11 13 10 11 17 19 12  9 10 19 16  9]
 [19 13 11  7 13 16  8 12  8 11 11  9  6 11 15  8]
 [45 24 30 14 24 29 18 24 25 30 23 19 17 29 32 18]
 [29 15 21  9 14 18 12 15 18 21 15 12 11 21 21 12]
 [25 16 13  9 17 20 10 17  9 13 14 13  7 13 19 10]
 [40 20 28 12 20 24 16 20 23 27 19 16 16 27 28 16]
 [29 17 18 10 18 22 12 17 14 17 16 14 10 17 22 12]
 [25 11 19  7 11 13 10 11 16 18 11  9 11 19 17  9]]
Error: 6.7025892164e-06


In [41]:
X3, k = IRLS_M(Y3, 3, 1)
print('X3')
print(X3.astype(int))
print('Error:', np.linalg.norm((Xtrue - X3), 'fro'))
#print((Xtrue - X3).astype(int))

X3
[[30 12 24  8 12 14 12 12 22 24 13 10 14 24 20 12]
 [30 21 15 11 21 26 12 21 10 15 17 15  8 15 23 12]
 [14  9  9  5  9 11  6  9  7  9  8  7  5  9 11  6]
 [35 16 25 10 16 19 13 16 23 26 17 13 15 26 24 14]
 [15  9  9  5  9 11  5  9  7  9  8  6  5  9 11  6]
 [24 11 19  7 11 13 10 11 17 19 12  9 11 19 17 10]
 [45 24 30 14 24 29 18 24 25 30 23 19 17 30 32 18]
 [30 14 21  9 15 18 12 15 18 21 15 12 12 21 21 12]
 [25 11 19  7 11 13 10 11 17 19 12  9 11 19 17 10]
 [19 13 11  7 13 16  8 13  8 11 11 10  6 11 15  8]
 [45 24 30 14 24 29 18 24 25 30 23 19 17 30 32 18]
 [30 15 21  9 15 18 12 15 18 21 15 12 12 21 21 12]
 [25 17 13  9 17 21 10 17  9 13 14 13  7 13 19 10]
 [40 20 28 12 20 24 16 20 23 28 20 16 16 28 28 16]
 [30 17 18 10 18 22 12 18 14 18 16 14 10 18 22 12]
 [25 11 19  7 11 13 10 11 17 19 12  9 11 19 17  9]]
Error: 3.42885482511e-07


## Q2 c)
---

In [42]:
gamma = [3, 2, 1, 0.5, 0.1, 0.01]
for i in gamma:
    X1, k = IRLS_M(Y1, 3, i)
    print("Gamma =", i, ", Error:", np.linalg.norm((Xtrue - X1), 'fro'))

Gamma = 3 , Error: 12.6938091154
Gamma = 2 , Error: 12.6938091154
Gamma = 1 , Error: 12.6938091154
Gamma = 0.5 , Error: 12.1753757731
Gamma = 0.1 , Error: 11.8730828699
Gamma = 0.01 , Error: 11.8643645163


## Q3
---

In [63]:
### DO NOT change
def ItSingValThresh(Y, r):
    """
    Iterative Singular Value Thresholding function for Matrix Completion
    Assumes elements of Y are integers between 0 and 10^6
    """
    tol = 10**(-6)  # difference between iterates at termination
    n,p = Y.shape 
    X = np.array(Y) #make a copy so operations do not mutate the original
    X[np.isnan(X)] = 0 # Fill in missing entries with zeros

    err = 10**6 
    k = 0
    while err > tol:
        U,s,VT = np.linalg.svd(X, full_matrices=False)
        V = VT.T ; S = np.diag(s)
        Xnew = (U[:,:r] @ S[:r,:r] @ V[:,:r].T).round()
        for i in range(n):
            for j in range(p):
                if Y[i,j] < 10**6 and Y[i,j] > 0:
                    Xnew[i,j] = Y[i,j]
        err = np.linalg.norm(X-Xnew,'fro') 
        X = Xnew
        k = k + 1
    return (X, k)

In [87]:
Xtrue = np.loadtxt(open("Xtrue.txt", "rb"), delimiter=" ")
Y = np.loadtxt(open("Y.txt", "rb"), delimiter=" ")

(200, 200)


In [90]:
start = time.time()
X, k = IRLS_M(Y, 5, 1)
end = time.time()
print('Running time:', end - start)
print('#Iter:', k)
print('Error:', np.linalg.norm((Xtrue - X), 'fro'))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
Running time: 104.54964399337769
#Iter: 37
Error: 4.86705635669e-07


In [91]:
start = time.time()
X, k = ItSingValThresh(Y, 5)
end = time.time()
print('Running time:', end - start)
print('#Iter:', k)
print('Error:', np.linalg.norm((Xtrue - X), 'fro'))

Running time: 0.9156858921051025
#Iter: 10
Error: 0.0
